Bookify.Presentation/Controllers/BookCopiesController.cs
namespace Bookify.Presentation.Controllers
{
	[Authorize]
	public class BookCopiesController : Controller
	{
		private readonly IBookCopyService _BookCopyService;
		private readonly IBookService _bookService;
		private readonly IMapper _mapper;
		private readonly IDataProtector _dataProtector;
		public BookCopiesController(IBookCopyService BookCopyService, IBookService bookService, IMapper mapper, IDataProtectionProvider dataProtector)
		{
			_BookCopyService = BookCopyService;
			_bookService = bookService;
			_mapper = mapper;
			_dataProtector = dataProtector.CreateProtector(purpose: "MySecureIds");
		}

		[HttpGet]
		public async Task<ActionResult<IList<BookCopyViewModel>>> Index()
		{
			var query = await _BookCopyService.GetAllAsync();

			foreach (var item in query)
				item.Id = _dataProtector.Protect(item.Id);

			return View(query);
		}

		[HttpGet("BookCopies/Details/{id}")]
		public async Task<ActionResult<BookCopyViewModel>> Details(string id)
		{
			var unprotectedId = UnprotectId(id);

			if (unprotectedId == null)
				return NotFound();

			var query = await _BookCopyService.GetByIdAsync(unprotectedId.Value);
			query.Id = id; // Keep on Protected Id

			return View(query);
		}

		[Authorize(Roles = DefaultRole.Admin)]
		public async Task<ActionResult> CreateForm(string BookId)
		{
			var unprotectedId = UnprotectId(BookId);

			if (unprotectedId == null)
				return NotFound();

			var book = await _bookService.GetByIdAsync(unprotectedId.Value);

			var model = new CreateBookCopyViewModel
			{
				BookId = unprotectedId.Value,
				ShowForRental = book.IsAvailableForRental
			};

			return View(model);
		}

		[HttpPost]
		[Authorize(Roles = DefaultRole.Admin)]
		public async Task<ActionResult> Create(CreateBookCopyViewModel request)
		{
			if (!ModelState.IsValid)
			{
				return View(request);
			}

			var id = await _BookCopyService.CreateAsync(request);

			TempData["successmessage"] = "Copy Added Successfully";

			var protectedId = _dataProtector.Protect(id.ToString());

			return RedirectToAction("Details", "Books",new { id = protectedId });
		}

		public async Task<IActionResult> Edit(string id)
		{
			var unprotectedId = UnprotectId(id);

			if (unprotectedId == null)
				return NotFound();

			var BookCopy = await _BookCopyService.GetByIdAsync(unprotectedId.Value);
			BookCopy.Id = id;

			return View(BookCopy);
		}

		[HttpPost("BookCopies/Edit/{id}")]
		[Authorize(Roles = DefaultRole.Admin)]
		public async Task<IActionResult> Edit(string id, CreateBookCopyViewModel request)
		{
			if (!ModelState.IsValid)
			{
				return View(request);
			}

			var unprotectedId = UnprotectId(id);

			if (unprotectedId == null)
				return NotFound();

			var bookId = await _BookCopyService.UpdateAsync(unprotectedId.Value, request);

			TempData["successmessage"] = "Book Updated Successfully";

			return RedirectToAction("Details", "Books", new { id  });
		}

		[Authorize(Roles = DefaultRole.Admin)]
		public async Task<IActionResult> DeleteForm(string id)
		{
			var unprotectedId = UnprotectId(id);

			if (unprotectedId == null)
				return NotFound();

			var BookCopy = await _BookCopyService.GetByIdAsync(unprotectedId.Value);
			BookCopy.Id = id;

			return View(BookCopy);
		}

		[HttpPost("BookCopies/Delete/{id}")]
		[Authorize(Roles = DefaultRole.Admin)]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Delete(string id)
		{
			var unprotectedId = UnprotectId(id);

			if (unprotectedId == null)
				return NotFound();

			await _BookCopyService.DeleteAsync(unprotectedId.Value);

			TempData["successmessage"] = "Status Toggled Successfully";

			return RedirectToAction(nameof(Index),"Books");
		}

		private int? UnprotectId(string protectedId)
		{
			try
			{
				return int.Parse(_dataProtector.Unprotect(protectedId));
			}
			catch
			{
				return null; // Return null for invalid IDs
			}
		}
	}
}

Bookify.Presentation/Controllers/BooksController.cs
namespace Bookify.Presentation.Controllers
{
	[Authorize]
	public class BooksController : Controller
	{
		private readonly IBookService _BookService;
		private readonly IAuthorService _AuthorService;
		private readonly ICategoryService _CategoryService;
		private readonly IMapper _mapper;
		private readonly IDataProtector _dataProtector;
		private readonly List<string> _extensions = new List<string>() { ".jpg", ".png", ".jpeg" };
		private readonly int _MaxSize = 2097152;
		public BooksController(IBookService BookService,
			IAuthorService authorService,
			IMapper mapper,
			ICategoryService categoryService,
			IDataProtectionProvider dataProtectionProvider)
		{
			_BookService = BookService;
			_AuthorService = authorService;
			_mapper = mapper;
			_CategoryService = categoryService;
			_dataProtector = dataProtectionProvider.CreateProtector(purpose: "MySecureKey");
		}

		public async Task<ActionResult<IList<BookViewModel>>> Index(string searchTerm = null)
		{
			var query = await _BookService.GetAllAsync();
			
			if(searchTerm != null)
				query = query.Where(x=> x.Title.ToLower().Contains(searchTerm.ToLower())).ToList();
			
			foreach(var item in query)
				item.Id = _dataProtector.Protect(item.Id.ToString());

			return View(query);
		}

		public async Task<ActionResult<BookViewModel>> Details(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			var query = await _BookService.GetByIdAsync(unprotectedId.Value);
			query.Id = id;

			foreach (var item in query.BookCopies)
				item.Id = _dataProtector.Protect(item.Id);

			return View(query);
		}

		[Authorize(Roles = DefaultRole.Admin)]
		public async Task<ActionResult> CreateForm()
		{
			var bookVm = await GetCreateBookViewModel();

			return View(bookVm);
		}

		[HttpPost]
        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<ActionResult> Create(CreateBookViewModel model)
		{
			await CheckImage(model);

			if (!ModelState.IsValid)
			{
				model = await GetCreateBookViewModel(model);

				return View(nameof(CreateForm),model);
			}

		    await _BookService.CreateAsync(model);

			TempData["successmessage"] = "Book Added Successfully";

			return RedirectToAction(nameof(Index));
		}

        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<IActionResult> Edit(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			var Book = await _BookService.GetByIdAsync(unprotectedId.Value);
            Book.Id = id;

			var Authors = await _AuthorService.GetAllAsync();

			var categories = await _CategoryService.GetAllAsync();

			Book.Authors = _mapper.Map<IList<SelectListItem>>(Authors);
			Book.CategoriesList = _mapper.Map<IList<SelectListItem>>(categories);

            return View(Book);
		}

		[HttpPost("Books/Edit/{id}")]
        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<IActionResult> Edit(string id,CreateBookViewModel model)
		{
			await CheckImage(model);

			if (!ModelState.IsValid)
			{
                var authors = await _AuthorService.GetAllAsync();
                var categories = await _CategoryService.GetAllAsync();

                var bookVM = _mapper.Map<BookViewModel>(model);

				bookVM.Authors = model.Authors;
				bookVM.CategoriesList = model.Categories;

                return View(bookVM);
			}

			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			await _BookService.UpdateAsync(unprotectedId.Value, model);

			TempData["successmessage"] = "Book Updated Successfully";

			return RedirectToAction(nameof(Index));
		}

        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<IActionResult> DeleteForm(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			var Book = await _BookService.GetByIdAsync(unprotectedId.Value);
			Book.Id = id;

			return View(Book);
		}

        [Authorize(Roles = DefaultRole.Admin)]
        [HttpPost("Books/Delete/{id}")]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Delete(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			await _BookService.DeleteAsync(unprotectedId.Value);

			TempData["successmessage"] = "Book Deleted Successfully";

			return RedirectToAction(nameof(Index));
		}

		private async Task<CreateBookViewModel> GetCreateBookViewModel(CreateBookViewModel? model = null)
		{
			CreateBookViewModel viewModel = model is null ? new CreateBookViewModel() : model;

			var authors = await _AuthorService.GetAllAsync();
			var categories = await _CategoryService.GetAllAsync();

			viewModel.Authors = _mapper.Map<IList<SelectListItem>>(authors);
			viewModel.Categories = _mapper.Map<IList<SelectListItem>>(categories);

			return viewModel;
		}

		private async Task<ActionResult> CheckImage(CreateBookViewModel model)
		{
			if (model.ImageUrl is not null)
			{
				if (!_extensions.Contains(Path.GetExtension(model.ImageUrl.FileName)))
				{
					ModelState.AddModelError("ImageExtension", ".jpg,.png,.jpeg are allowed only.");

					model = await GetCreateBookViewModel(model);

					return View(nameof(CreateForm), model);
				}

				if (model.ImageUrl.Length > _MaxSize)
				{
					ModelState.AddModelError("ImageSize", "Size of Image must't be greater than 2Mb .");

					model = await GetCreateBookViewModel(model);

					return View(nameof(CreateForm), model);
				}
			}

			return null!;
		}

		private int? UnProtectedId(string id)
		{
			int protectedId;

			try
			{
				protectedId = int.Parse(_dataProtector.Unprotect(id));

				return protectedId;
			}
			catch 
			{
				return null;
			}
		}
	}
}

Bookify.Presentation/Views/Books/CreateForm.cshtml
@model CreateBookViewModel

@{
	ViewData["Title"] = "Add New Book";
}

<div class="row p-4">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
				<h5 class="text-center my-2">Create New Book</h5>
			</div>
			<div class="card-body">
				<form asp-action="Create" asp-controller="Books" method="post" enctype="multipart/form-data">
					<div class="row">
						<div class="col-md-6 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Title" class="form-control my-2" placeholder="Title" />
								<span asp-validation-for="Title" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-6 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Description" class="form-control my-2" placeholder="Description" />
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="number" asp-for="Price" class="form-control my-2" placeholder="Price" />
								<span asp-validation-for="Price" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Publisher" class="form-control my-2" placeholder="Publisher" />
								<span asp-validation-for="Publisher" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="date" asp-for="PublishedOn" class="form-control js-flatpickr my-2" placeholder="PublishedOn" />
								<span asp-validation-for="PublishedOn" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-8 col-12">
							<div class="form-group my-2">
								<input type="file" asp-for="ImageUrl" class="form-control my-2" placeholder="Image" />
								<span asp-validation-for="ImageUrl" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Type" class="form-control my-2" placeholder="Type" />
								<span asp-validation-for="Type" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Hall" class="form-control my-2" placeholder="Hall" />
								<span asp-validation-for="Hall" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-8 col-12">
							<div class="form-group my-2">
								<select asp-items="@Model.Authors" asp-for="AuthorId" class="form-select js-select2" aria-label="Default select example">
									<option value="0" selected>-- select Author --</option>
									@foreach (var item in Model.Authors!)
									{
										<option value="@item.Value">@item.Text</option>
									}
								</select>
								<span asp-validation-for="AuthorId" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6 col-12">
							<div class="form-group d-flex justify-content-between my-2">
								<!--Make it Rdio -->
								<label class="form-label">Is Available For Rental</label>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="IsAvailableForRental" id="flexRadioDefault1" value="true">
									<label class="form-check-label" for="flexRadioDefault1">
										Yes
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="IsAvailableForRental" id="flexRadioDefault2" value="false" checked>
									<label class="form-check-label" for="flexRadioDefault2">
										No
									</label>
								</div>
								<span asp-validation-for="IsAvailableForRental" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-12">
							<div class="form-group my-2">
								<h5>Select Categories</h5>
								<div class="row">
									@foreach (var category in Model.Categories!)
									{
										<div class="col-md-4">
											<div class="form-check">
												<input class="form-check-input" type="checkbox" name="SelectedCategories" id="category-@category.Value" value="@category.Value">
												<label class="form-check-label" for="category-@category.Value">@category.Text</label>
											</div>
										</div>
									}
								</div>
								<span asp-validation-for="@Model.SelectedCategories" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-12">
							<input type="submit" value="Save" class="btn btn-primary d-block ms-auto my-2" />
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />

	<script>
		$(document).ready(function(){
			ApplySelect2();
		    ApplyflatPickr();
		})
	</script>
}

Bookify.Presentation/Views/Books/Details.cshtml
@model BookViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="row card p-4 mb-3">
    <div class="col-12">
        <div class="row p-4">
            <div class="col-md-4 col-12">
                <img src="~/assets/images/@Model.ImageUrl" class="img-fluid h-100 rounded-start" alt="@Model.Title" style="object-fit: cover" />
            </div>
            <div class="col-md-8 col-12">
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text"><strong>Price:</strong> @Model.Price</p>
                    <p class="card-text"><strong>Author:</strong> @Model.AuthorName</p>
                    <p class="card-text"><strong>Publisher:</strong> @Model.Publisher</p>
                    <p class="card-text"><strong>Published On:</strong> @Model.PublishedOn.ToString("yyyy-MM-dd")</p>
                    <p class="card-text"><strong>Hall:</strong> @Model.Hall</p>
                    <p class="card-text"><strong>Available for Rental:</strong> @Model.IsAvailableForRental</p>
                    <p class="card-text"><strong>Type:</strong> @Model.Type</p>
                    <p class="card-text"><strong>Copies:</strong> @Model.BookCopies.Count()</p>
                    <p class="card-text"><strong>Categories:</strong> @string.Join(" - ", Model.SelectedCategories!)</p>
                    <div class="d-flex justify-content-between">
                        <a asp-action="Index" asp-controller="Books" class="btn btn-warning my-2">Back To List</a>
                        @if (User.IsInRole(DefaultRole.Admin))
                        {    
                           <a asp-action="Edit" asp-controller="Books" asp-route-id="@Model.Id" class="btn btn-primary my-2">Edit</a>
                        }
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="d-flex gap-2">
            <a href="#" class="my-2 Description-link">Description</a>
            <a href="#" class="my-2 Copies-link">Copies</a>
        </div>
    </div>
</div>

<div class="row card p-4 mt-2">
    @if (User.IsInRole(DefaultRole.Admin))
    {
        <div class="col-12 text-end">
            <a href="/BookCopies/CreateForm?BookId=@Model.Id" class="btn btn-primary my-3">Add New Copy</a>
            @* <a href="javascript:;" data-url="/BookCopies/CreateForm?BookId=@Model.Id" class="btn btn-primary my-3">Add New Copy</a> *@
        </div>
    }
   
    <div class="col-12 js-table">
        <!--Displaying Copies and description-->
        @if (Model.BookCopies.Count() > 0)
        {
            <table class="table table-hover table-responsive table-borderless table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Status</th>
                        <th></th>
                        <th>Is Available For Rental?</th>
                        <th></th>
                        <th>Edition Number</th>
                        <th></th>
                        <th>Serial Number</th>
                        <th></th>
                        <th>Actions</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var copy in Model.BookCopies)
                    {
                        <tr>
                            <td></td>
                            <td>@copy.Title</td>
                            <td>
                                @if (!copy.IsDeleted)
                                {
                                    <span class="badge bg-success js-status">Available</span>
                                }else
                                {
                                    <span class="badge bg-danger js-status">Deleted</span>
                                }
                            </td>
                            <td></td>
                            <td>@copy.IsAvailableForRental</td>
                            <td></td>
                            <td>@copy.EditionNumber</td>
                            <td></td>
                            <td>@copy.SerialNumber</td>
                            <td></td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                        Actions
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <li>
                                            <a class="dropdown-item active" asp-action="Details" asp-controller="BookCopies" asp-route-id="@copy.Id"><i class="bi bi-eye-fill"></i> Details</a>
                                        </li>
										@if (User.IsInRole(DefaultRole.Admin))
										{
											<li>
												<a class="dropdown-item" asp-action="Edit" asp-controller="BookCopies" asp-route-id="@copy.Id"><i class="bi bi-box-arrow-in-down-left"></i> Update</a>
											</li>
											<li>
												<a href="javascript:;" class="dropdown-item js-toggle-status" data-url="/BookCopies/Delete/@copy.Id"><i class="bi bi-trash-fill"></i> Toggle Status</a>
											</li>
										}
                                    </ul>
                                </div>
                            </td>
                            <td></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-dismissible alert-warning">
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                <h4 class="alert-heading">Warning!</h4>
                <p class="mb-0">Not Exist Copies For That Book <a href="#" class="alert-link">vel scelerisque nisl consectetur et</a>.</p>
            </div>
        }
    </div>
    <div class="col-12 js-des d-none">@Model.Description</div>
</div>

<!--AntiForignToken-->
@Html.AntiForgeryToken()

<!-- Ajax && JQuery-->
@section Scripts {
    <script src="~/js/book.js" asp-append-version="true"></script>
}

@if (TempData["successmessage"] != null)
{
    @section scripts2 {
    <script>
        SweetAlertMessage('@TempData["successmessage"]')
    </script>
    }
}

Bookify.Presentation/Views/Books/Edit.cshtml
@model BookViewModel

@{
	ViewData["Title"] = "Edit Book";
}

<div class="row p-4">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
				<h5 class="text-center my-2">Update @Model.Title Book</h5>
			</div>
			<div class="card-body">
				<form asp-action="Edit" asp-controller="Books" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
					<div class="row">
						<div class="col-md-6 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Title" class="form-control my-2" placeholder="Title" />
								<span asp-validation-for="Title" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-6 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Description" class="form-control my-2" placeholder="Description" />
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="number" asp-for="Price" class="form-control my-2" placeholder="Price" />
								<span asp-validation-for="Price" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Publisher" class="form-control my-2" placeholder="Publisher" />
								<span asp-validation-for="Publisher" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="date" asp-for="PublishedOn" class="form-control my-2" placeholder="PublishedOn" />
								<span asp-validation-for="PublishedOn" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-8 col-12">
							<div class="form-group my-2">
								<input type="file" asp-for="ImageUrl" class="form-control my-2" placeholder="Image" />
								<span asp-validation-for="ImageUrl" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Type" class="form-control my-2" placeholder="Type" />
								<span asp-validation-for="Type" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-4 col-12">
							<div class="form-group my-2">
								<input type="text" asp-for="Hall" class="form-control my-2" placeholder="Hall" />
								<span asp-validation-for="Hall" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-8 col-12">
							<div class="form-group my-2">
								<select asp-items="@Model.Authors" name="AuthorId" class="form-select" aria-label="Default select example">
									<option value="0">-- select Author --</option>
									@foreach (var item in Model.Authors!)
									{
										if(item.Text == Model.AuthorName)
										{
											<option value="@item.Value" selected>@item.Text</option>
										}
										else
										{
											<option value="@item.Value">@item.Text</option>
										}
									}
								</select>
								<span asp-validation-for="AuthorName" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6 col-12">
							<div class="form-group d-flex justify-content-between my-2">
								<!--Make it Rdio -->
								<label class="form-label">Is Available For Rental</label>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="IsAvailableForRental" id="flexRadioDefault1" value="true">
									<label class="form-check-label" for="flexRadioDefault1">
										Yes
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="IsAvailableForRental" id="flexRadioDefault2" value="false" checked>
									<label class="form-check-label" for="flexRadioDefault2">
										No
									</label>
								</div>
								<span asp-validation-for="IsAvailableForRental" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-12">
							<div class="form-group my-2">
								<h5>Select Categories</h5>
								<div class="row">
									@foreach (var category in Model.CategoriesList!)
									{
										<div class="col-md-4">
											<div class="form-check">
												<input class="form-check-input" type="checkbox" name="SelectedCategories" id="category-@category" value="@category.Value" @(Model.SelectedCategories.Contains(category.Text) ? "checked" : "")>
												<label class="form-check-label" for="category-@category">@category.Text</label>
											</div>
										</div>
									}
								</div>
								<span asp-validation-for="@Model.SelectedCategories" class="text-danger"></span>
							</div>
						</div>
					</div>


					<div class="row">
						<div class="col-12">
							<input type="submit" value="Save" class="btn btn-primary d-block ms-auto my-2" />
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Bookify.Presentation/Views/Books/Index.cshtml
@model IList<BookViewModel>

@{
	ViewData["Title"] = "Books";
}

<div class="row d-flex justify-content-center p-4">
    <div class="col-10">
        <form asp-action="Index" asp-controller="Books" method="get" class="d-flex justify-content-between gap-1">
          <input type="text" name="searchTerm" class="form-control my-2" placeholder="Search By Title..."/>
          <input type="submit" value="search" class="btn btn-warning my-2" />
        </form>
    </div>
</div>

<div class="row p-4">
    <div class="col-12">
       
        @if (User.IsInRole(DefaultRole.Admin))
        {
            <div class="d-flex justify-content-end mb-2">
                <a asp-action="CreateForm" asp-controller="Books" class="btn btn-primary">Create New Book</a>
            </div>
        }
        <div class="row">
            @foreach (var book in Model)
            {
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card text-decoration-none text-dark">
                        <a asp-controller="Books" asp-action="Details" asp-route-id="@book.Id" class="card-img-top">
                            <img src="~/assets/images/@book.ImageUrl" class="img-fluid" alt="@book.Title" />
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">@book.Title</h5>
                            <p class="card-text text-muted">@book.Description</p>
                            <p class="card-text"><strong>Price:</strong> @book.Price</p>
                            <p class="card-text"><strong>Author:</strong> @book.AuthorName</p>
                            <p class="card-text"><strong>Publisher:</strong> @book.Publisher</p>
                            <p class="card-text"><strong>Published On:</strong> @book.PublishedOn.ToString("yyyy-MM-dd")</p>
                            <p class="card-text"><strong>Hall:</strong> @book.Hall</p>
                            <p class="card-text"><strong>Available for Rental:</strong> @book.IsAvailableForRental</p>
                            <p class="card-text"><strong>Type:</strong> @book.Type</p>
                            <p class="card-text"><strong>Categories:</strong> @string.Join(" - ", @book.SelectedCategories!)</p>
                            <div class="d-flex justify-content-between mt-2">
                                @if (User.IsInRole(DefaultRole.Admin))
                                {
                                   <a asp-action="Edit" asp-controller="Books" asp-route-id="@book.Id" class="btn btn-warning">Update</a>
                                }
                                <a asp-controller="Books" asp-action="Details" asp-route-id="@book.Id" class="btn btn-primary">View Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@if (TempData["successmessage"] is not null)
{
	@section Scripts {
	<script>
		$(document).ready(function () {
			SweetAlertMessage('@TempData["successmessage"]')
			})
		</script>
	}
}