Bookify.Presentation/Controllers/BooksController.cs
namespace Bookify.Presentation.Controllers
{
	[Authorize]
	public class BooksController : Controller
	{
		private readonly IBookService _BookService;
		private readonly IAuthorService _AuthorService;
		private readonly ICategoryService _CategoryService;
		private readonly IMapper _mapper;
		private readonly IDataProtector _dataProtector;
		private readonly List<string> _extensions = new List<string>() { ".jpg", ".png", ".jpeg" };
		private readonly int _MaxSize = 2097152;
		public BooksController(IBookService BookService,
			IAuthorService authorService,
			IMapper mapper,
			ICategoryService categoryService,
			IDataProtectionProvider dataProtectionProvider)
		{
			_BookService = BookService;
			_AuthorService = authorService;
			_mapper = mapper;
			_CategoryService = categoryService;
			_dataProtector = dataProtectionProvider.CreateProtector(purpose: "MySecureKey");
		}

		public async Task<ActionResult<IList<BookViewModel>>> Index(string searchTerm = null)
		{
			var query = await _BookService.GetAllAsync();
			
			if(searchTerm != null)
				query = query.Where(x=> x.Title.ToLower().Contains(searchTerm.ToLower())).ToList();
			
			foreach(var item in query)
				item.Id = _dataProtector.Protect(item.Id.ToString());

			return View(query);
		}

		public async Task<ActionResult<BookViewModel>> Details(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			var query = await _BookService.GetByIdAsync(unprotectedId.Value);
			query.Id = id;

			foreach (var item in query.BookCopies)
				item.Id = _dataProtector.Protect(item.Id);

			return View(query);
		}

		[Authorize(Roles = DefaultRole.Admin)]
		public async Task<ActionResult> CreateForm()
		{
			var bookVm = await GetCreateBookViewModel();

			return View(bookVm);
		}

		[HttpPost]
        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<ActionResult> Create(CreateBookViewModel model)
		{
			await CheckImage(model);

			if (!ModelState.IsValid)
			{
				model = await GetCreateBookViewModel(model);

				return View(nameof(CreateForm),model);
			}

		    await _BookService.CreateAsync(model);

			TempData["successmessage"] = "Book Added Successfully";

			return RedirectToAction(nameof(Index));
		}

        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<IActionResult> Edit(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			var Book = await _BookService.GetByIdAsync(unprotectedId.Value);
            Book.Id = id;

			var Authors = await _AuthorService.GetAllAsync();

			var categories = await _CategoryService.GetAllAsync();

			Book.Authors = _mapper.Map<IList<SelectListItem>>(Authors);
			Book.CategoriesList = _mapper.Map<IList<SelectListItem>>(categories);

            return View(Book);
		}

		[HttpPost("Books/Edit/{id}")]
        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<IActionResult> Edit(string id,CreateBookViewModel model)
		{
			await CheckImage(model);

			if (!ModelState.IsValid)
			{
                var authors = await _AuthorService.GetAllAsync();
                var categories = await _CategoryService.GetAllAsync();

                var bookVM = _mapper.Map<BookViewModel>(model);

				bookVM.Authors = model.Authors;
				bookVM.CategoriesList = model.Categories;

                return View(bookVM);
			}

			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			await _BookService.UpdateAsync(unprotectedId.Value, model);

			TempData["successmessage"] = "Book Updated Successfully";

			return RedirectToAction(nameof(Index));
		}

        [Authorize(Roles = DefaultRole.Admin)]
        public async Task<IActionResult> DeleteForm(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			var Book = await _BookService.GetByIdAsync(unprotectedId.Value);
			Book.Id = id;

			return View(Book);
		}

        [Authorize(Roles = DefaultRole.Admin)]
        [HttpPost("Books/Delete/{id}")]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Delete(string id)
		{
			var unprotectedId = UnProtectedId(id);

			if (unprotectedId is null)
				return NotFound();

			await _BookService.DeleteAsync(unprotectedId.Value);

			TempData["successmessage"] = "Book Deleted Successfully";

			return RedirectToAction(nameof(Index));
		}

		private async Task<CreateBookViewModel> GetCreateBookViewModel(CreateBookViewModel? model = null)
		{
			CreateBookViewModel viewModel = model is null ? new CreateBookViewModel() : model;

			var authors = await _AuthorService.GetAllAsync();
			var categories = await _CategoryService.GetAllAsync();

			viewModel.Authors = _mapper.Map<IList<SelectListItem>>(authors);
			viewModel.Categories = _mapper.Map<IList<SelectListItem>>(categories);

			return viewModel;
		}

		private async Task<ActionResult> CheckImage(CreateBookViewModel model)
		{
			if (model.ImageUrl is not null)
			{
				if (!_extensions.Contains(Path.GetExtension(model.ImageUrl.FileName)))
				{
					ModelState.AddModelError("ImageExtension", ".jpg,.png,.jpeg are allowed only.");

					model = await GetCreateBookViewModel(model);

					return View(nameof(CreateForm), model);
				}

				if (model.ImageUrl.Length > _MaxSize)
				{
					ModelState.AddModelError("ImageSize", "Size of Image must't be greater than 2Mb .");

					model = await GetCreateBookViewModel(model);

					return View(nameof(CreateForm), model);
				}
			}

			return null!;
		}

		private int? UnProtectedId(string id)
		{
			int protectedId;

			try
			{
				protectedId = int.Parse(_dataProtector.Unprotect(id));

				return protectedId;
			}
			catch 
			{
				return null;
			}
		}
	}
}

Bookify.Presentation/Controllers/UsersController.cs
namespace Bookify.Presentation.Controllers
{
    [Authorize(Roles = DefaultRole.Admin)]
    public class UsersController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        private readonly IEmailSender _emailSender;
        private readonly IEmailBodyBuilder _emailBuilder;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IMapper _mapper;
        public UsersController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, IEmailSender emailSender, IMapper mapper, IWebHostEnvironment webHostEnvironment, IEmailBodyBuilder emailBuilder)
        {
            _userManager = userManager;
            _mapper = mapper;
            _roleManager = roleManager;
            _emailSender = emailSender;
            _webHostEnvironment = webHostEnvironment;
            _emailBuilder = emailBuilder;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Select(x => new UserViewModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                UserName = x.UserName!,
                Email = x.Email!
            })
                .ToListAsync();

            if(users is null)
            {
                return NotFound();
            }

            return View(users);
        }

        public async Task<IActionResult> Create()
        {
            var roles = await _roleManager.Roles.Select(x => new SelectListItem
            {
                Value = x.Name, // because AddToRole(user,NameOfRoleNotId)
                Text = x.Name
            })
                .ToListAsync();

            var model = new CreateUserViewModel()
            {
                Roles = roles
            };

            return View(model);
        }

        #region Create User without divide action
        //[HttpPost]
        //public async Task<IActionResult> Create(CreateUserViewModel model)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(model);
        //    }

        //    var email = await _userManager.FindByEmailAsync(model.Email);

        //    if (email is not null)
        //    {
        //        ModelState.AddModelError("Error: ", "Email is already in use");

        //        return View(model);
        //    }

        //    var UserName = await _userManager.FindByNameAsync(model.Email.Split('@')[0]);

        //    if (UserName is not null)
        //    {
        //        ModelState.AddModelError("Error: ", "UserName is already in use");

        //        return View(model);
        //    }


        //    var user = _mapper.Map<AppUser>(model);
        //    user.UserName = model.Email.Split('@')[0];

        //    var result = await _userManager.CreateAsync(user, model.Password);

        //    if (result.Succeeded)
        //    {
        //        if (model.SelectedRoles is not null)
        //        {
        //            await _userManager.AddToRolesAsync(user, model.SelectedRoles.AsEnumerable());
        //        }

        //        var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
        //        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
        //        var callbackUrl = Url.Page(
        //            "/Account/ConfirmEmail",
        //            pageHandler: null,
        //            values: new { area = "Identity", userId = user.Id, code = code },
        //            protocol: Request.Scheme);

        //        // Full URL for image
        //        string imageUrl = $"{Request.Scheme}://{Request.Host}/assets/images/Screenshot.png"; // for images that on server
        //        string? imageFromGoogle = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s";

        //        // Replace placeholders in email template
        //        var body = await _emailBuilder.GenerateEmailBody(imageFromGoogle, header: $"Hi {user.FirstName}, We’re proud to have you join us!",
        //                                      body: "Please Confirm Your Email",
        //                                      link: $"{HtmlEncoder.Default.Encode(callbackUrl!)}",
        //                                      linkTitle: "Activate account");

        //        await _emailSender.SendEmailAsync(user.Email!, "Confirm your email", body);

        //        TempData["successmessage"] = "User Added Successfully";
        //        return RedirectToAction(nameof(Index));
        //    }
        //    else
        //    {
        //        var error = result.Errors.First();
        //        ModelState.AddModelError("Error: ", error.Description);
        //    }

        //    return View(model);
        //}
        #endregion

        #region Create User Action with Divide action on small methods
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Validate email and username availability
            if (!await IsEmailAvailable(model.Email) || !await IsUserNameAvailable(model.Email))
            {
                return View(model);
            }

            // Create user
            var user = await MapUser(model);
            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                await AssignRoles(user, model.SelectedRoles);

                // Generate confirmation email
                var emailBody = await GenerateEmailBody(user);

                await _emailSender.SendEmailAsync(user.Email!, "Confirm your email", emailBody);

                TempData["successmessage"] = "User Added Successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var error = result.Errors.First();
                ModelState.AddModelError("Error: ", error.Description);
            }

            return View(model);
        }

        // Helper Method 1: Check if email is available
        private async Task<bool> IsEmailAvailable(string email)
        {
            var existingEmail = await _userManager.FindByEmailAsync(email);
            if (existingEmail != null)
            {
                ModelState.AddModelError("Error: ", "Email is already in use");
                return false;
            }
            return true;
        }

        // Helper Method 2: Check if username is available
        private async Task<bool> IsUserNameAvailable(string email)
        {
            var userName = email.Split('@')[0];
            var existingUserName = await _userManager.FindByNameAsync(userName);
            if (existingUserName != null)
            {
                ModelState.AddModelError("Error: ", "UserName is already in use");
                return false;
            }
            return true;
        }

        // Helper Method 3: Map ViewModel to User
        private async Task<AppUser> MapUser(CreateUserViewModel model)
        {
            var user = _mapper.Map<AppUser>(model);
            user.UserName = model.Email.Split('@')[0];
            return user;
        }

        // Helper Method 4: Assign Roles to User
        private async Task AssignRoles(AppUser user, IEnumerable<string>? roles)
        {
            if (roles != null)
            {
                await _userManager.AddToRolesAsync(user, roles.AsEnumerable());
            }
        }

        // Helper Method 5: Generate Email Body
        private async Task<string> GenerateEmailBody(AppUser user)
        {
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
                "/Account/ConfirmEmail",
                pageHandler: null,
                values: new { area = "Identity", userId = user.Id, code = code },
                protocol: Request.Scheme);

            string imageUrl = $"{Request.Scheme}://{Request.Host}/assets/images/Screenshot.png";
            string? imageFromGoogle = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s";

            var body = await _emailBuilder.GenerateEmailBody("emailTemplate.html", imageFromGoogle,header: $"Hi {user.FirstName}, We’re proud to have you join us!",
                body: "Please Confirm Your Email",
                link: $"{HtmlEncoder.Default.Encode(callbackUrl!)}",
                linkTitle: "Activate account");

            return body;
        }

        #endregion

        public async Task<IActionResult> Edit(string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            var UserViewModel = await GetUserViewModel(user,null);

            return View(UserViewModel);
        }

        [HttpPost("Users/Edit")]
        public async Task<IActionResult> Edit(int id,CreateUserViewModel model)
        {
            var existedUser = await _userManager.FindByIdAsync(id.ToString());

            if (existedUser == null)
            {
                ModelState.AddModelError("", "User not found");
                return View(nameof(Edit), await GetUserViewModel(null, model));
            }

            if (!ModelState.IsValid)
            {
                return View(nameof(Edit), await GetUserViewModel(existedUser,model));
            }

            var user = _mapper.Map(model,existedUser);

            user!.UserName = model.Email.Split('@')[0];

            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                if (model.SelectedRoles is not null)
                {

Bookify.Presentation/Controllers/ٍSearchController.cs
namespace Bookify.Presentation.Controllers
{
    public class SearchController : Controller
    {
        private readonly IDataProtector _protector;
        private readonly IBookService _bookService;
        public SearchController(IDataProtectionProvider dataProtection, IBookService bookService)
        {
            _protector = dataProtection.CreateProtector(purpose: "SecureKey");
            _bookService = bookService;
        }


        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View();
        }

        // to display book details , implemtation it is like Details that exist in BookController,you can use Details that exist in BookController too...
        [HttpGet("Search/Details/{id}")]
        public async Task<ActionResult> Details(string id)
        {
            var unprotectedId = int.Parse(_protector.Unprotect(id));

            var book = await _bookService.GetByIdAsync(unprotectedId);

            return View(book);
        }

        // for Typeahead package

        [HttpGet]
        public async Task<IActionResult> FindBook(string search)
        {
            var books = await _bookService.FindAsync(search);

            foreach (var book in books)
            {
                book.Id = _protector.Protect(book.Id.ToString());
            }

            return Ok(books); // must return Ok Or Json Not View
        }
    }
}

Bookify.Presentation/Views/Shared/_DataTablesJsScriptsPartial.cshtml
    <!--Add DataTables JS Files-->
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables/js/datatables.bootstrap4.min.js"></script> <!--Must be after jquery.datatables.min.js-->
    <!--Js Files that belong Buttons in DataTables-->
    <script src="~/lib/datatables-buttons/js/datatables.buttons.min.js"></script>
	<script src="~/lib/datatables.net-buttons-bs5/buttons.bootstrap5.min.js"></script>
    <script src="~/lib/jszip/jszip.min.js"></script>
    <script src="~/lib/pdfmake/pdfmake.min.js"></script>
    <script src="~/lib/pdfmake/vfs_fonts.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.print.min.js"></script>

Bookify.Presentation/Views/Shared/_FooterPartial.cshtml
<footer class="border-top footer text-muted text-center">
<div class="container">
	&copy; 2024 - Bookify - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>
</footer>

Bookify.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookify</title>
    <link rel="stylesheet" href="~/bootstrapwatch/bootstrap.min (3).css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css"/>

    <!--font-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded:wght@100;200;300;400;500;600;700;800;900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded:wght@100;200;300;400;500;600;700;800;900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Satisfy&display=swap" rel="stylesheet">
    <!--Animate Css file-->
    <link  rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
    
    <!--Toastr css files-->
	<link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />

    <!--Add Sweetalert2 css Package link-->
	<link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />

    <!--Add DataTables CSS Files-->
    <link href="~/lib/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
	<link href="~/lib/datatables.net-buttons-bs5/buttons.bootstrap5.min.css" rel="stylesheet" /> <!--Belong to Buttons of DataTables-->

    <!--Add Select2 Library CSS File-->

    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />

    <!-- Add ApexCharts CSS File-->
    <link rel="stylesheet" href="~/lib/apexcharts/apexcharts.min.css"/>

    <!--Add flatpickr package CSS File-->

    <link rel="stylesheet" href="~/lib/flatpickr/flatpickr.min.css"/>

    @await RenderSectionAsync(name: "Styles",required: false)

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/Bookify.styles.css" asp-append-version="true" /> *@


</head>
<body>
     <noscript>
         <div class="position-fixed text-center bg-white h-100 w-100 p-4" style="z-index:30000000;">
             <h3 class="text-danger fw-bold my-2">JavaScript is Disabled</h3>
             <p class="text-muted my-2">PLease allow browser to use JavaScript and reload the Page again</p>
         </div>
    </noscript>
    <partial name="_NavBarPartial"/>
    
    <div class="container animate__animated animate__fadeInTopLeft">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

     <partial name="_FooterPartial"/>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Add Bootbox js Package link-->
	<script src="~/lib/bootbox.js/bootbox.min.js"></script>

    <!--Add Toastr js Package link-->
	<script src="~/lib/toastr.js/toastr.min.js"></script>

    <!--Add Sweetalert2 js Package link-->
	<script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>

    <!--Add Select2 Library Js File-->

    <script src="~/lib/select2/js/select2.min.js"></script>

    <!--Add flatPicker Package Js File-->

    <script src="~/lib/flatpickr/flatpickr.min.js"></script>

    <!-- Add ApexCharts JS File-->

    <script src="~/lib/apexcharts/apexcharts.min.js"></script>

    @await RenderSectionAsync("CustomScripts",required: false);

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Scripts2", required: false)
    
</body>
</html>

Bookify.Presentation/Views/Shared/_NavBarPartial.cshtml
@using System.Security.Claims
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light fw-bold bg-primary border-bottom box-shadow mb-3">
        <div class="container-fluid">
            @if (!User.Identity!.IsAuthenticated)
            {
                <a class="navbar-brand" href="#"><img src="~/assets/images/Instruction manual-cuate.png" width="50" height="50" /></a>
            }
            else
            {
              <a class="navbar-brand" style="margin-left:30px" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/assets/images/Instruction manual-cuate.png" width="50" height="50" /></a>
            }
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dashboard" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index"><i class="bi bi-tags"></i> Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Authors" asp-action="Index"><i class="bi bi-people"></i> Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Books" asp-action="Index"><i class="bi bi-book"></i> Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Subscribers" asp-action="Index"><i class="bi bi-envelope"></i> Subscribers</a>
                        </li>
                       
                        @if (User.IsInRole(DefaultRole.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Index"><i class="bi bi-person"></i> Users</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Search" asp-action="Index"><i class="bi bi-search"></i> Search</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav">
                   
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <span class="nav-link text-light">Hello @User.FindFirstValue(ClaimTypes.GivenName)</span>
                        </li>
@*                         <li class="nav-item">
                    <span class="nav-link text-light">Hello @User.Identity.Name</span>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Manage/Index">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/LogOut">LogOut</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>
</header>

Bookify.Presentation/Views/Shared/_asidePartial.cshtml
<aside class="col-12 bg-light p-3 border-end">
    <nav>
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="/Dashboard"><i class="bi bi-house"></i> Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Authors"><i class="bi bi-people"></i> Authors</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Categories"><i class="bi bi-tags"></i> Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Users"><i class="bi bi-person"></i> Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Dashboard/Books"><i class="bi bi-book"></i> Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/Subscribes"><i class="bi bi-envelope"></i> Subscribes</a>
            </li>
        </ul>
    </nav>
</aside>